// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: secretbox.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_secretbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secretbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_secretbox_proto_rawDescGZIP(), []int{0}
}

func (x *GetSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSecretRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_secretbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secretbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_secretbox_proto_rawDescGZIP(), []int{1}
}

func (x *GetSecretResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_secretbox_proto protoreflect.FileDescriptor

const file_secretbox_proto_rawDesc = "" +
	"\n" +
	"\x0fsecretbox.proto\x12\x17presenter.grpc.proto.v1\"<\n" +
	"\x10GetSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"+\n" +
	"\x11GetSecretResponse\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret2v\n" +
	"\x10SecretBoxService\x12b\n" +
	"\tGetSecret\x12).presenter.grpc.proto.v1.GetSecretRequest\x1a*.presenter.grpc.proto.v1.GetSecretResponseB4Z2github.com/teran/secretbox/presenter/grpc/proto/v1b\x06proto3"

var (
	file_secretbox_proto_rawDescOnce sync.Once
	file_secretbox_proto_rawDescData []byte
)

func file_secretbox_proto_rawDescGZIP() []byte {
	file_secretbox_proto_rawDescOnce.Do(func() {
		file_secretbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secretbox_proto_rawDesc), len(file_secretbox_proto_rawDesc)))
	})
	return file_secretbox_proto_rawDescData
}

var file_secretbox_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_secretbox_proto_goTypes = []any{
	(*GetSecretRequest)(nil),  // 0: presenter.grpc.proto.v1.GetSecretRequest
	(*GetSecretResponse)(nil), // 1: presenter.grpc.proto.v1.GetSecretResponse
}
var file_secretbox_proto_depIdxs = []int32{
	0, // 0: presenter.grpc.proto.v1.SecretBoxService.GetSecret:input_type -> presenter.grpc.proto.v1.GetSecretRequest
	1, // 1: presenter.grpc.proto.v1.SecretBoxService.GetSecret:output_type -> presenter.grpc.proto.v1.GetSecretResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_secretbox_proto_init() }
func file_secretbox_proto_init() {
	if File_secretbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secretbox_proto_rawDesc), len(file_secretbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_secretbox_proto_goTypes,
		DependencyIndexes: file_secretbox_proto_depIdxs,
		MessageInfos:      file_secretbox_proto_msgTypes,
	}.Build()
	File_secretbox_proto = out.File
	file_secretbox_proto_goTypes = nil
	file_secretbox_proto_depIdxs = nil
}
